version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Fibre-Channel Pool Example

  To run this example you need to execute:

  ```bash
  $ terraform init
  $ terraform plan
  $ terraform apply
  ```

  Note that this example will create resources. Resources can be destroyed with `terraform destroy`.

  ### main.tf
  ```hcl
  {{ include "./main.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "./variables.tf" }}
  ```

  ### versions.tf
  ```hcl
  {{ include "./versions.tf" }}
  ```

output:
  file: README.md
  mode: replace